### ISSUE TITLE
mailactivation энэ хичээл дээр  AppServiceProvider дээр гарсан алдаа.

### ISSUE THREAD

**Issue by redaced** [felagund18/lessons#1]
AppServiceProvider ийн \Notification::send($user, new ActivationCodeRequested); энэ мөр нь дээр Class 'App\Providers\ActivationCodeRequested' not found ийм алдаа гараад байх юм. Тэгээд уг нь бол sublime ийн goto definition аар харахаар зөв заагаад байгаа мөртөлөө.

**Comment by felagund18** [comment]
```
use \App\Notifications\ActivationCodeRequested;
```
мөр код бичиж өгөх ёстойг устгачихаж :)
