### ISSUE TITLE
Laravel 5.3 - ALC 

### ISSUE THREAD

**Issue by rubenscarrilho** [felagund18/lessons#2]
This is simple Laravel 5.3 CRUD with authentication and 2 tables, Drivers and Vehicles.

I want to control who can access the Drivers link and who can access Vehicles link, and then who can have acces for Create, Update and Delete
 
[crud_lara53.zip](https://github.com/felagund18/lessons/files/542389/crud_lara53.zip)

**Comment by felagund18** [comment]
Hi @rubenscarrilho, I have reviewed your code and there are 2 possible ways to do this ACL...
## 1. Role based access
Your web will have 2 main roles, maybe 3...
1. DriverManager role that manages Drivers. Users in this group can manage only drivers...
2. VehicleManager role that manages Vehicles.
3. UserManager role that manages Users.

When UserManager registers a new user, the manager can bind the new user to any roles...

Steps to implement role based access (RBAC)
**1. Create Role model**
```
php artisan make:model Role
```
**2. Make new migration for Role**
```
php artisan make:migration create_roles_table
```
And the migration must be like this.
```
<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateRolesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('roles', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->string('code');
            $table->timestamps();
        });

        \DB::table('roles')->insert(['name' => 'Driver manager', 'code' => 'driver']);
        \DB::table('roles')->insert(['name' => 'Vehicle manager', 'code' => 'vehicle']);
        
        Schema::create('role_user', function(Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id');
            $table->integer('role_id');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('roles');
        Schema::drop('role_user');
    }
}
```
And then run migrate command
```
php artisan migrate
```
**3. Add new relation to model Role**
```
public function users () {
    return $this->belongsToMany(‘\App\User’);
}
```
**4. Add new relation to model User**
```
public function roles () {
    return $this->belongsToMany(‘\App\Role’);
}
```
**5. Define role access gates**
In a file ```/app/Providers/AuthServiceProvider.php```, you must defines those gates
```
    public function boot(GateContract $gate)
    {
        $this->registerPolicies($gate);

        //DriverManager role access
        $gate->define('driver-access', function ($user) {
            foreach ($user->roles as $role) {
                if ($role->code == 'driver') {
                    return true;
                }
            }
            return false;
        });
        
        //VehicleManager role access
        $gate->define('vehicle-access', function ($user) {
            foreach ($user->roles as $role) {
                if ($role->code == 'vehicle') {
                    return true;
                }
            }
            return false;
        });
    }
```

Now you have created all things you needed...

**6. Final step. Example usage**
```
class DriversController extends Controller
{	
	/**
	 * Display a listing of the resource.
	 * @return \Illuminate\Http\Response
	 */
	public function index()
	{
                 if (\Gate::allows('admin-access')) {
                          $drivers = Drivers::all();
                          return view( 'drivers' , compact( 'drivers' ) );
                 }
                 throw new Exception('Forbidden page.', 403);
	}

```

## 2. Per user permissions

**Comment by rubenscarrilho** [comment]
I dont think so that this is the best way to do that, because if I have 200 pages, the /app/Providers/AuthServiceProvider.php will get huge.
 I'll try to do something here to show you.

Otherwise thank you very much

**Comment by felagund18** [comment]
Well even if you 200 pages ```/app/Providers/AuthServiceProvider.php``` will not get huge, but if you have 200 roles the ```/app/Providers/AuthServiceProvider.php``` will get huge...

In your case, you have only 2 roles ```driver-manager, vehicle-manager```, so it wont be any problem 👍

**Comment by rubenscarrilho** [comment]
Yes, I agree, but look this diagram, it can be dynamically more efficient and it doesn't matter if you have 1 or 1000 roles and 2000 pages... Did you understand ???

[Laravel5.3-Users-Roles-PermissionsandPages.pdf](https://github.com/felagund18/lessons/files/551144/Laravel5.3-Users-Roles-PermissionsandPages.pdf)
